/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Administrador extends javax.swing.JFrame {
    
    String user, nombre_usuario;
    
    public static int Secion_usuario;

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/Logo Final.png")));
        user = Log_in.user;
        Secion_usuario = 1;
        
        setSize(944, 494);
        setResizable(false);
        
        setLocationRelativeTo(null);
        setTitle("Administrador - Secion de " + user);
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select nombre_usuario from usuarios where username = '" + user + "' ");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                nombre_usuario = rs.getString("nombre_usuario");
                etiketa_Bienbenida.setText("Secion de " + nombre_usuario);
            }
        } catch (Exception e) {
            System.err.println("erro en la coneccion en la interfaz administrador");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        boton_GestionarInsumos5 = new javax.swing.JButton();
        boton_agregar_insumo1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        boton_GestionarInsumos4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        boton_GestionarInsumos3 = new javax.swing.JButton();
        boton_GestionarInsumos2 = new javax.swing.JButton();
        boton_GestionarInsumos1 = new javax.swing.JButton();
        boton_GestionarInsumos = new javax.swing.JButton();
        botton_Minimisar = new javax.swing.JButton();
        boton_agregar_insumo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        boton_Cerrar = new javax.swing.JButton();
        etiketa_Bienbenida = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        boton_ganancias = new javax.swing.JButton();
        boton_actualizar_Precio = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        etiketa_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(88, 56, 28));
        jLabel10.setText("Calculadora");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(88, 56, 28));
        jLabel9.setText("Agregar Usuario");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, -1, -1));

        boton_GestionarInsumos5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono.png"))); // NOI18N
        boton_GestionarInsumos5.setContentAreaFilled(false);
        boton_GestionarInsumos5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono1.png"))); // NOI18N
        boton_GestionarInsumos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_GestionarInsumos5ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_GestionarInsumos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 140, 130));

        boton_agregar_insumo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        boton_agregar_insumo1.setContentAreaFilled(false);
        boton_agregar_insumo1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar1.png"))); // NOI18N
        boton_agregar_insumo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_agregar_insumo1ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_agregar_insumo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 140, 130));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(88, 56, 28));
        jLabel8.setText("Costo unitario");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, -1, -1));

        boton_GestionarInsumos4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a.png"))); // NOI18N
        boton_GestionarInsumos4.setContentAreaFilled(false);
        boton_GestionarInsumos4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a1.png"))); // NOI18N
        boton_GestionarInsumos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_GestionarInsumos4ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_GestionarInsumos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 140, 130));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(88, 56, 28));
        jLabel7.setText("Aserca De");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        boton_GestionarInsumos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ganancias_1.png"))); // NOI18N
        boton_GestionarInsumos3.setContentAreaFilled(false);
        boton_GestionarInsumos3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ganancias1.png"))); // NOI18N
        boton_GestionarInsumos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_GestionarInsumos3ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_GestionarInsumos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 140, 130));

        boton_GestionarInsumos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aserca_de.png"))); // NOI18N
        boton_GestionarInsumos2.setContentAreaFilled(false);
        boton_GestionarInsumos2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aserca_de.1png.png"))); // NOI18N
        boton_GestionarInsumos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_GestionarInsumos2ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_GestionarInsumos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 130, 130));

        boton_GestionarInsumos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/insumos.png"))); // NOI18N
        boton_GestionarInsumos1.setContentAreaFilled(false);
        boton_GestionarInsumos1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/insumos1.png"))); // NOI18N
        boton_GestionarInsumos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_GestionarInsumos1ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_GestionarInsumos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 130));

        boton_GestionarInsumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresos.png"))); // NOI18N
        boton_GestionarInsumos.setContentAreaFilled(false);
        boton_GestionarInsumos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresos1.jpg.png"))); // NOI18N
        boton_GestionarInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_GestionarInsumosActionPerformed(evt);
            }
        });
        getContentPane().add(boton_GestionarInsumos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 130, 130));

        botton_Minimisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimisar.png"))); // NOI18N
        botton_Minimisar.setContentAreaFilled(false);
        botton_Minimisar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimisar2.png"))); // NOI18N
        botton_Minimisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_MinimisarActionPerformed(evt);
            }
        });
        getContentPane().add(botton_Minimisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 50, 50));

        boton_agregar_insumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo insumo.png"))); // NOI18N
        boton_agregar_insumo.setContentAreaFilled(false);
        boton_agregar_insumo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar insumo2.png"))); // NOI18N
        boton_agregar_insumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_agregar_insumoActionPerformed(evt);
            }
        });
        getContentPane().add(boton_agregar_insumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 140, 130));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(88, 56, 28));
        jLabel5.setText("Ganancias");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        boton_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        boton_Cerrar.setContentAreaFilled(false);
        boton_Cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar2.png"))); // NOI18N
        boton_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_CerrarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 60, 50));

        etiketa_Bienbenida.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        etiketa_Bienbenida.setForeground(new java.awt.Color(88, 33, 12));
        etiketa_Bienbenida.setText("jLabel1");
        getContentPane().add(etiketa_Bienbenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(88, 56, 28));
        jLabel2.setText("Gestionar ingresos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(88, 56, 28));
        jLabel1.setText("Actualizar Precio");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(88, 56, 28));
        jLabel3.setText("Insertar insumo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(88, 56, 28));
        jLabel4.setText("Registros");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        boton_ganancias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ganancias.png"))); // NOI18N
        boton_ganancias.setContentAreaFilled(false);
        boton_ganancias.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ganancias2.png"))); // NOI18N
        boton_ganancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_gananciasActionPerformed(evt);
            }
        });
        getContentPane().add(boton_ganancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 140, 130));

        boton_actualizar_Precio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/precio.png"))); // NOI18N
        boton_actualizar_Precio.setContentAreaFilled(false);
        boton_actualizar_Precio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/precio2.png"))); // NOI18N
        boton_actualizar_Precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_actualizar_PrecioActionPerformed(evt);
            }
        });
        getContentPane().add(boton_actualizar_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 140, 130));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(88, 56, 28));
        jLabel6.setText("Gestionar insumos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        etiketa_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_Ad.png"))); // NOI18N
        getContentPane().add(etiketa_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 950, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_actualizar_PrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_actualizar_PrecioActionPerformed
        Cambiar_precio mensajero = new Cambiar_precio();
        mensajero.setVisible(true);
    }//GEN-LAST:event_boton_actualizar_PrecioActionPerformed

    private void boton_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_CerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_boton_CerrarActionPerformed

    private void botton_MinimisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_MinimisarActionPerformed
        this.setState(Log_in.ICONIFIED);
    }//GEN-LAST:event_botton_MinimisarActionPerformed

    private void boton_agregar_insumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_agregar_insumoActionPerformed
        Agregar_Insumo mensajero = new Agregar_Insumo();
        mensajero.setVisible(true);
    }//GEN-LAST:event_boton_agregar_insumoActionPerformed

    private void boton_gananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_gananciasActionPerformed
        Ganancias mensajero = new Ganancias();
        mensajero.setVisible(true);
    }//GEN-LAST:event_boton_gananciasActionPerformed

    private void boton_GestionarInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_GestionarInsumosActionPerformed
        Gestionar_ingresos mensajero = new Gestionar_ingresos();
        mensajero.setVisible(true);
    }//GEN-LAST:event_boton_GestionarInsumosActionPerformed

    private void boton_GestionarInsumos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_GestionarInsumos1ActionPerformed
        
        Gestionar_insumos mensajero = new Gestionar_insumos();
        mensajero.setVisible(true);
    }//GEN-LAST:event_boton_GestionarInsumos1ActionPerformed

    private void boton_GestionarInsumos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_GestionarInsumos2ActionPerformed
        JOptionPane.showMessageDialog(null, "Creador: Sobera Sotomayor Iñaki\n"
                + "(Para cualquier fallo en el sistema, porfavor comunicate\n"
                + "al 5539357116)");
    }//GEN-LAST:event_boton_GestionarInsumos2ActionPerformed

    private void boton_GestionarInsumos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_GestionarInsumos3ActionPerformed
        Ingresos mensajero = new Ingresos();
        mensajero.setVisible(true);
    }//GEN-LAST:event_boton_GestionarInsumos3ActionPerformed

    private void boton_GestionarInsumos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_GestionarInsumos4ActionPerformed
        Gestionar_Insumo mensajero = new Gestionar_Insumo();
        mensajero.setVisible(true);
    }//GEN-LAST:event_boton_GestionarInsumos4ActionPerformed

    private void boton_agregar_insumo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_agregar_insumo1ActionPerformed
        Gestionar_Usuarios mensajero = new Gestionar_Usuarios();
        mensajero.setVisible(true);
    }//GEN-LAST:event_boton_agregar_insumo1ActionPerformed

    private void boton_GestionarInsumos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_GestionarInsumos5ActionPerformed
        Calculadora mensajero = new Calculadora();
        mensajero.setVisible(true);
    }//GEN-LAST:event_boton_GestionarInsumos5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Cerrar;
    private javax.swing.JButton boton_GestionarInsumos;
    private javax.swing.JButton boton_GestionarInsumos1;
    private javax.swing.JButton boton_GestionarInsumos2;
    private javax.swing.JButton boton_GestionarInsumos3;
    private javax.swing.JButton boton_GestionarInsumos4;
    private javax.swing.JButton boton_GestionarInsumos5;
    private javax.swing.JButton boton_actualizar_Precio;
    private javax.swing.JButton boton_agregar_insumo;
    private javax.swing.JButton boton_agregar_insumo1;
    private javax.swing.JButton boton_ganancias;
    private javax.swing.JButton botton_Minimisar;
    private javax.swing.JLabel etiketa_Bienbenida;
    private javax.swing.JLabel etiketa_Fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    public void botones() {
        
        boton_actualizar_Precio.setOpaque(false);
        boton_actualizar_Precio.setBorderPainted(false);
        boton_actualizar_Precio.setContentAreaFilled(false);
        
        boton_agregar_insumo.setOpaque(false);
        boton_agregar_insumo.setBorderPainted(false);
        boton_agregar_insumo.setContentAreaFilled(false);
        
        boton_ganancias.setOpaque(false);
        boton_ganancias.setBorderPainted(false);
        boton_ganancias.setContentAreaFilled(false);
        
    }
    
    private Gestionar_insumos Gestionar_insumos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
}
