/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author user
 */
public class Agregar_Insumo extends javax.swing.JFrame {

    String Fecha, insumo, precio;
    int precioo;
    String Dia, Mes, Annio;
        String fecha;
    
    String user;
    int bandera = 0;

    /**
     * Creates new form Cambiar_precio
     */
    public Agregar_Insumo() {
        initComponents();
        user = Log_in.user;
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/Logo Final.png")));
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        

        Calendar cl = Calendar.getInstance();
        Dia = Integer.toString(cl.get(Calendar.DATE));
        Mes = Integer.toString(cl.get(Calendar.MONTH) + 1);
        Annio = Integer.toString(cl.get(Calendar.YEAR));

        fecha = Dia + "/" + Mes + "/" + Annio;

        txt_Dia.setText(fecha);
        
        setSize(849, 547);
        setResizable(false);//metodo para rue el usuario no modifique mi interfas
        setLocationRelativeTo(null);//metodo para sentrar mi interfas
        setTitle("Agregar insumo -secion de " + user);//pongo el titulo

       
     
        txt_Dia.setVisible(false);
        txt_Precio.setVisible(false);
        txt_insumo.setVisible(false);
        Boton_registrar.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Dia = new javax.swing.JTextField();
        txt_Precio = new javax.swing.JTextField();
        txt_insumo = new javax.swing.JTextField();
        boton_Cerrar = new javax.swing.JButton();
        Boton_Azucar = new javax.swing.JButton();
        etiketa_insumo = new javax.swing.JLabel();
        etiketa_precio = new javax.swing.JLabel();
        etiketa_Dia = new javax.swing.JLabel();
        boton_Crema = new javax.swing.JButton();
        Boton_registrar = new javax.swing.JButton();
        boton_cafe = new javax.swing.JButton();
        boton_servicio = new javax.swing.JButton();
        boton_Vasos1 = new javax.swing.JButton();
        boton_Agua = new javax.swing.JButton();
        boton_Paletinas = new javax.swing.JButton();
        boton_chocolate = new javax.swing.JButton();
        boton_Capuchino = new javax.swing.JButton();
        etiketa_Like = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtP_Instrucciones = new javax.swing.JTextArea();
        etiketa_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Dia.setBackground(new java.awt.Color(0, 0, 0));
        txt_Dia.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txt_Dia.setForeground(new java.awt.Color(255, 255, 255));
        txt_Dia.setEnabled(false);
        getContentPane().add(txt_Dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 310, 60));

        txt_Precio.setEditable(false);
        txt_Precio.setBackground(new java.awt.Color(0, 0, 0));
        txt_Precio.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txt_Precio.setForeground(new java.awt.Color(255, 255, 255));
        txt_Precio.setEnabled(false);
        getContentPane().add(txt_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 330, 60));

        txt_insumo.setBackground(new java.awt.Color(0, 0, 0));
        txt_insumo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txt_insumo.setForeground(new java.awt.Color(255, 255, 255));
        txt_insumo.setDoubleBuffered(true);
        txt_insumo.setEnabled(false);
        getContentPane().add(txt_insumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 310, 60));

        boton_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        boton_Cerrar.setContentAreaFilled(false);
        boton_Cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar2.png"))); // NOI18N
        boton_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_CerrarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 60, 50));

        Boton_Azucar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/azucar.png"))); // NOI18N
        Boton_Azucar.setContentAreaFilled(false);
        Boton_Azucar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/azucar2.png"))); // NOI18N
        Boton_Azucar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_AzucarActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Azucar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 70, -1));

        etiketa_insumo.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        etiketa_insumo.setForeground(new java.awt.Color(255, 255, 255));
        etiketa_insumo.setText("Selecciona el Insumo:");
        getContentPane().add(etiketa_insumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 290, 30));

        etiketa_precio.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        etiketa_precio.setForeground(new java.awt.Color(255, 255, 255));
        etiketa_precio.setText("...");
        getContentPane().add(etiketa_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 280, 30));

        etiketa_Dia.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        etiketa_Dia.setForeground(new java.awt.Color(255, 255, 255));
        etiketa_Dia.setText("Dia del registro:");
        getContentPane().add(etiketa_Dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 280, 30));

        boton_Crema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crema.png"))); // NOI18N
        boton_Crema.setContentAreaFilled(false);
        boton_Crema.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crema2.png"))); // NOI18N
        boton_Crema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_CremaActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Crema, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 60, 110));

        Boton_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar_insumo.png"))); // NOI18N
        Boton_registrar.setContentAreaFilled(false);
        Boton_registrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar_insumo1.png"))); // NOI18N
        Boton_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 350, 110));

        boton_cafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cafe.png"))); // NOI18N
        boton_cafe.setContentAreaFilled(false);
        boton_cafe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boton_cafe.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cafe2.png"))); // NOI18N
        boton_cafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cafeActionPerformed(evt);
            }
        });
        getContentPane().add(boton_cafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 90, 110));

        boton_servicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Servicio.png"))); // NOI18N
        boton_servicio.setContentAreaFilled(false);
        boton_servicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boton_servicio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Servicio1.png"))); // NOI18N
        boton_servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_servicioActionPerformed(evt);
            }
        });
        getContentPane().add(boton_servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 90, 110));

        boton_Vasos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vasos.png"))); // NOI18N
        boton_Vasos1.setContentAreaFilled(false);
        boton_Vasos1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boton_Vasos1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/basos2.png"))); // NOI18N
        boton_Vasos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Vasos1ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Vasos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 80, 110));

        boton_Agua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agua.png"))); // NOI18N
        boton_Agua.setContentAreaFilled(false);
        boton_Agua.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boton_Agua.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agua2.png"))); // NOI18N
        boton_Agua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_AguaActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Agua, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 70, 110));

        boton_Paletinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paletinas.png"))); // NOI18N
        boton_Paletinas.setContentAreaFilled(false);
        boton_Paletinas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boton_Paletinas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paletinas2.png"))); // NOI18N
        boton_Paletinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_PaletinasActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Paletinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 90, 110));

        boton_chocolate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chocolate.png"))); // NOI18N
        boton_chocolate.setContentAreaFilled(false);
        boton_chocolate.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chocolate2.png"))); // NOI18N
        boton_chocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_chocolateActionPerformed(evt);
            }
        });
        getContentPane().add(boton_chocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 90, 110));

        boton_Capuchino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caouchino.png"))); // NOI18N
        boton_Capuchino.setContentAreaFilled(false);
        boton_Capuchino.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boton_Capuchino.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/capuchino2.png"))); // NOI18N
        boton_Capuchino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_CapuchinoActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Capuchino, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 70, 110));
        getContentPane().add(etiketa_Like, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 130, 120));

        txtP_Instrucciones.setBackground(new java.awt.Color(0, 0, 0));
        txtP_Instrucciones.setColumns(20);
        txtP_Instrucciones.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        txtP_Instrucciones.setForeground(new java.awt.Color(255, 255, 255));
        txtP_Instrucciones.setRows(5);
        txtP_Instrucciones.setText("A qui se escrviran las instrucciones que mandes al prohrama");
        txtP_Instrucciones.setEnabled(false);
        jScrollPane1.setViewportView(txtP_Instrucciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 420, 300));

        etiketa_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondi_I.png"))); // NOI18N
        getContentPane().add(etiketa_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 849, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_AzucarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_AzucarActionPerformed
        bandera = 1;
        
        ImageIcon verde = new ImageIcon("src/imagenes/Azucar Verde.png");
        Boton_Azucar.setIcon(verde);
        
        Fecha();

        txt_insumo.setText("Azucar");

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "SELECT azucar FROM precios");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_Precio.setText(rs.getString("azucar"));
            }

        } catch (SQLException e) {
            System.err.println("error al buscar el precio de la azucar");
        }
        txtP_Instrucciones.setText("has seleccionado el boton\n"
                + "Azucar, para el registro preciona \n"
                + "el boton Registrar");

        txt_Dia.setVisible(true);
        txt_Precio.setVisible(true);
        txt_insumo.setVisible(true);
        Boton_registrar.setVisible(true);

    }//GEN-LAST:event_Boton_AzucarActionPerformed

    private void boton_CremaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_CremaActionPerformed
        bandera = 2;
        
        ImageIcon verde = new ImageIcon("src/imagenes/crema_verde.png");
        boton_Crema.setIcon(verde);
        
        Fecha();

        txt_insumo.setText("crema");

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "SELECT crema FROM precios");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_Precio.setText(rs.getString("crema"));
            }

        } catch (SQLException e) {
            System.err.println("error al buscar el precio de la crema");
        }
        txtP_Instrucciones.setText("has seleccionado el boton\n"
                + "crema, para el registro preciona \n"
                + "el boton Registrar");

        txt_Dia.setVisible(true);
        txt_Precio.setVisible(true);
        txt_insumo.setVisible(true);
        Boton_registrar.setVisible(true);


    }//GEN-LAST:event_boton_CremaActionPerformed

    private void boton_cafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cafeActionPerformed
        bandera = 4;
            
        ImageIcon verde = new ImageIcon("src/imagenes/cafeVerde.png");
        boton_cafe.setIcon(verde);
        
        Fecha();

        txt_insumo.setText("cafe");

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "SELECT cafe FROM precios");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_Precio.setText(rs.getString("cafe"));
            }

        } catch (SQLException e) {
            System.err.println("error al buscar el precio de la cafe");
        }
        txtP_Instrucciones.setText("has seleccionado el boton\n"
                + "cafe, para el registro preciona \n"
                + "el boton Registrar");

        txt_Dia.setVisible(true);
        txt_Precio.setVisible(true);
        txt_insumo.setVisible(true);
        Boton_registrar.setVisible(true);


    }//GEN-LAST:event_boton_cafeActionPerformed

    private void boton_chocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_chocolateActionPerformed

        bandera = 3;
        
        ImageIcon verde = new ImageIcon("src/imagenes/chocolateVerde.png");
        boton_chocolate.setIcon(verde);
        
        Fecha();

        txt_insumo.setText("chocolate");

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "SELECT chocolate FROM precios");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_Precio.setText(rs.getString("chocolate"));
            }

        } catch (SQLException e) {
            System.err.println("error al buscar el precio de la chocolate");
        }
        txtP_Instrucciones.setText("has seleccionado el boton\n"
                + "chocolate, para el registro preciona \n"
                + "el boton Registrar");

        txt_Dia.setVisible(true);
        txt_Precio.setVisible(true);
        txt_insumo.setVisible(true);
        Boton_registrar.setVisible(true);


    }//GEN-LAST:event_boton_chocolateActionPerformed

    private void boton_servicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_servicioActionPerformed
        bandera = 9;
        
        
        ImageIcon verde = new ImageIcon("src/imagenes/servicioVerde.png");
        boton_servicio.setIcon(verde);

        
        Fecha();

        txt_insumo.setText("servicio");

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "SELECT servicio FROM precios");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_Precio.setText(rs.getString("servicio"));
            }

        } catch (SQLException e) {
            System.err.println("error al buscar el precio de la servicio");
        }
        txtP_Instrucciones.setText("has seleccionado el boton\n"
                + "servicio, para el registro preciona \n"
                + "el boton Registrar");

        txt_Dia.setVisible(true);
        txt_Precio.setVisible(true);
        txt_insumo.setVisible(true);
        Boton_registrar.setVisible(true);


    }//GEN-LAST:event_boton_servicioActionPerformed

    private void boton_CapuchinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_CapuchinoActionPerformed

        bandera = 5;
        
        ImageIcon verde = new ImageIcon("src/imagenes/capuchinoVerde.png");
        boton_Capuchino.setIcon(verde);
        
        Fecha();

        txt_insumo.setText("capuchino");

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "SELECT capuchino FROM precios");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_Precio.setText(rs.getString("capuchino"));
            }

        } catch (SQLException e) {
            System.err.println("error al buscar el precio de la capuchino");
        }
        txtP_Instrucciones.setText("has seleccionado el boton\n"
                + "capuchino, para el registro preciona \n"
                + "el boton Registrar");

        txt_Dia.setVisible(true);
        txt_Precio.setVisible(true);
        txt_insumo.setVisible(true);
        Boton_registrar.setVisible(true);


    }//GEN-LAST:event_boton_CapuchinoActionPerformed

    private void boton_AguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_AguaActionPerformed

        bandera = 7;
        
        
        ImageIcon verde = new ImageIcon("src/imagenes/agua verde.png");
        boton_Agua.setIcon(verde);
        
        Fecha();

        txt_insumo.setText("agua");

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "SELECT agua FROM precios");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_Precio.setText(rs.getString("agua"));
            }

        } catch (SQLException e) {
            System.err.println("error al buscar el precio de la agua");
        }
        txtP_Instrucciones.setText("has seleccionado el boton\n"
                + "agua, para el registro preciona \n"
                + "el boton Registrar");

        txt_Dia.setVisible(true);
        txt_Precio.setVisible(true);
        txt_insumo.setVisible(true);
        Boton_registrar.setVisible(true);


    }//GEN-LAST:event_boton_AguaActionPerformed

    private void boton_PaletinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_PaletinasActionPerformed
        bandera = 8;
        
        
        ImageIcon verde = new ImageIcon("src/imagenes/palerinas Verdes.png");
        boton_Paletinas.setIcon(verde);
        
        Fecha();

        txt_insumo.setText("paletinas");

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "SELECT paletinas FROM precios");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_Precio.setText(rs.getString("paletinas"));
            }

        } catch (SQLException e) {
            System.err.println("error al buscar el precio de la paletinas");
        }
        txtP_Instrucciones.setText("has seleccionado el boton\n"
                + "paletinas, para el registro preciona \n"
                + "el boton Registrar");

        txt_Dia.setVisible(true);
        txt_Precio.setVisible(true);
        txt_insumo.setVisible(true);
        Boton_registrar.setVisible(true);

    }//GEN-LAST:event_boton_PaletinasActionPerformed

    private void boton_Vasos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Vasos1ActionPerformed
        bandera = 6;
        
        ImageIcon verde = new ImageIcon("src/imagenes/vaso verde.png");
        boton_Vasos1.setIcon(verde);
        
        Fecha();

        txt_insumo.setText("tira_de_vasos");

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "SELECT tira_de_vasos FROM precios");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_Precio.setText(rs.getString("tira_de_vasos"));
            }

        } catch (SQLException e) {
            System.err.println("error al buscar el precio de la tira_de_vasos");
        }
        txtP_Instrucciones.setText("has seleccionado el boton\n"
                + "tira_de_vasos, para el registro preciona \n"
                + "el boton Registrar");

        txt_Dia.setVisible(true);
        txt_Precio.setVisible(true);
        txt_insumo.setVisible(true);
        Boton_registrar.setVisible(true);


    }//GEN-LAST:event_boton_Vasos1ActionPerformed

    private void boton_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_CerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_boton_CerrarActionPerformed

    private void Boton_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_registrarActionPerformed
        Fecha = txt_Dia.getText().trim();
        precio = txt_Precio.getText().trim();
        insumo = txt_insumo.getText().trim();
        precioo = Integer.parseInt(precio);
        if(bandera == 0){
            JOptionPane.showMessageDialog(null, "Deves seleccionar un insumo");
        }else{
        try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "INSERT INTO `insumos` values (?,?,?,?,?,?)");
                        
                pst.setInt(1, 0);
                pst.setString(2, insumo);
                pst.setString(3, Dia);
                pst.setString(4, Mes);
                pst.setString(5, Annio);
                pst.setInt(6, precioo);
                
                pst.executeUpdate();
                cn.close();
                
                
                
            } catch (SQLException e) {
                System.err.println("error al insertar los nuevs valores en la vase de datos");
            }
        if(bandera == 1){
            like();
            txtP_Instrucciones.setText("Se inserto " + insumo + "\n"
                    + "El Dia " + Fecha + " con el precio\n"
                            + precio);
            JOptionPane.showMessageDialog(null, "se inserto el insumo " + insumo + "con exito");
        }else if(bandera == 2){
            like();
            txtP_Instrucciones.setText("Se inserto " + insumo + "\n"
                    + "El Dia " + Fecha + " con el precio\n"
                            + precio);
            JOptionPane.showMessageDialog(null, "se inserto el insumo " + insumo + "con exito");
        }else if(bandera == 3){
            like();
            txtP_Instrucciones.setText("Se inserto " + insumo + "\n"
                    + "El Dia " + Fecha + " con el precio\n"
                            + precio);
            JOptionPane.showMessageDialog(null, "se inserto el insumo " + insumo + "con exito");
        }else if ( bandera == 4){
            like();
            txtP_Instrucciones.setText("Se inserto " + insumo + "\n"
                    + "El Dia " + Fecha + " con el precio\n"
                            + precio);
            JOptionPane.showMessageDialog(null, "se inserto el insumo " + insumo + "con exito");
        }else if (bandera == 5){
            like();
            txtP_Instrucciones.setText("Se inserto " + insumo + "\n"
                    + "El Dia " + Fecha + " con el precio\n"
                            + precio);
            JOptionPane.showMessageDialog(null, "se inserto el insumo " + insumo + "con exito");
            
        }else if (bandera == 6){
            like();
            txtP_Instrucciones.setText("Se inserto " + insumo + "\n"
                    + "El Dia " + Fecha + " con el precio\n"
                            + precio);
            JOptionPane.showMessageDialog(null, "se inserto el insumo " + insumo + "con exito");
        }else if (bandera == 7){
            like();
            txtP_Instrucciones.setText("Se inserto " + insumo + "\n"
                    + "El Dia " + Fecha + " con el precio\n"
                            + precio);
            JOptionPane.showMessageDialog(null, "se inserto el insumo " + insumo + "con exito");
        }else if (bandera ==7){
            like();
            txtP_Instrucciones.setText("Se inserto " + insumo + "\n"
                    + "El Dia " + Fecha + " con el precio\n"
                            + precio);
            JOptionPane.showMessageDialog(null, "se inserto el insumo " + insumo + "con exito");
        }else if (bandera == 8){
            like();
            txtP_Instrucciones.setText("Se inserto " + insumo + "\n"
                    + "El Dia " + Fecha + " con el precio\n"
                            + precio);
            JOptionPane.showMessageDialog(null, "se inserto el insumo " + insumo + "con exito");
        }else if(bandera == 9){
            like();
            txtP_Instrucciones.setText("Se inserto " + insumo + "\n"
                    + "El Dia " + Fecha + " con el precio\n"
                            + precio);
            JOptionPane.showMessageDialog(null, "se inserto el insumo " + insumo + "con exito");
        }
    }

    }//GEN-LAST:event_Boton_registrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_Insumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_Insumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_Insumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_Insumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_Insumo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Azucar;
    private javax.swing.JButton Boton_registrar;
    private javax.swing.JButton boton_Agua;
    private javax.swing.JButton boton_Capuchino;
    private javax.swing.JButton boton_Cerrar;
    private javax.swing.JButton boton_Crema;
    private javax.swing.JButton boton_Paletinas;
    private javax.swing.JButton boton_Vasos1;
    private javax.swing.JButton boton_cafe;
    private javax.swing.JButton boton_chocolate;
    private javax.swing.JButton boton_servicio;
    private javax.swing.JLabel etiketa_Dia;
    private javax.swing.JLabel etiketa_Fondo;
    private javax.swing.JLabel etiketa_Like;
    private javax.swing.JLabel etiketa_insumo;
    private javax.swing.JLabel etiketa_precio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtP_Instrucciones;
    private javax.swing.JTextField txt_Dia;
    private javax.swing.JTextField txt_Precio;
    private javax.swing.JTextField txt_insumo;
    // End of variables declaration//GEN-END:variables

    public void Fecha() {
        
    }

    public void like() {
        ImageIcon like = new ImageIcon("src/imagenes/like.png");
        etiketa_Like.setIcon(like);
    }

}
