/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Toolkit;
import javax.script.ScriptEngine;
import javax.swing.WindowConstants;
import javax.script.ScriptEngineManager;
/**
 *
 * @author user
 */
public class Calculadora extends javax.swing.JFrame {

    ScriptEngineManager sem = new ScriptEngineManager();
    ScriptEngine se = sem.getEngineByName("JavaScript");
    
    public Calculadora() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icono.png")));
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton_Igual = new javax.swing.JButton();
        boton_Menos = new javax.swing.JButton();
        boton_Mas = new javax.swing.JButton();
        boton_Entre = new javax.swing.JButton();
        boton_6 = new javax.swing.JButton();
        boton_Por = new javax.swing.JButton();
        boton_7 = new javax.swing.JButton();
        boton_8 = new javax.swing.JButton();
        boton_9 = new javax.swing.JButton();
        boton_P = new javax.swing.JButton();
        boton_5 = new javax.swing.JButton();
        boton_2 = new javax.swing.JButton();
        boton_3 = new javax.swing.JButton();
        boton_4 = new javax.swing.JButton();
        boton_0 = new javax.swing.JButton();
        boton_C = new javax.swing.JButton();
        boton_1 = new javax.swing.JButton();
        etiketa_Resultado = new javax.swing.JLabel();
        etiketa_Operacion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        etiketa_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_Igual.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        boton_Igual.setForeground(new java.awt.Color(255, 255, 255));
        boton_Igual.setText("=");
        boton_Igual.setContentAreaFilled(false);
        boton_Igual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_Igual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AMARILLO.png"))); // NOI18N
        boton_Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_IgualActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 80, 70));

        boton_Menos.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        boton_Menos.setForeground(new java.awt.Color(139, 152, 169));
        boton_Menos.setText("-");
        boton_Menos.setContentAreaFilled(false);
        boton_Menos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_Menos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BOTTON.png"))); // NOI18N
        boton_Menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_MenosActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Menos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 80, 70));

        boton_Mas.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        boton_Mas.setForeground(new java.awt.Color(139, 152, 169));
        boton_Mas.setText("+");
        boton_Mas.setContentAreaFilled(false);
        boton_Mas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_Mas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BOTTON.png"))); // NOI18N
        boton_Mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_MasActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 210, 80, 70));

        boton_Entre.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        boton_Entre.setForeground(new java.awt.Color(139, 152, 169));
        boton_Entre.setText("/");
        boton_Entre.setContentAreaFilled(false);
        boton_Entre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_Entre.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BOTTON.png"))); // NOI18N
        boton_Entre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_EntreActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Entre, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 210, 80, 70));

        boton_6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        boton_6.setForeground(new java.awt.Color(139, 152, 169));
        boton_6.setText("6");
        boton_6.setContentAreaFilled(false);
        boton_6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AB.png"))); // NOI18N
        boton_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_6ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 80, 70));

        boton_Por.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        boton_Por.setForeground(new java.awt.Color(139, 152, 169));
        boton_Por.setText("X");
        boton_Por.setContentAreaFilled(false);
        boton_Por.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_Por.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BOTTON.png"))); // NOI18N
        boton_Por.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_PorActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Por, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 80, 70));

        boton_7.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        boton_7.setForeground(new java.awt.Color(139, 152, 169));
        boton_7.setText("7");
        boton_7.setContentAreaFilled(false);
        boton_7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AB.png"))); // NOI18N
        boton_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_7ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 300, 80, 70));

        boton_8.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        boton_8.setForeground(new java.awt.Color(139, 152, 169));
        boton_8.setText("8");
        boton_8.setContentAreaFilled(false);
        boton_8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AB.png"))); // NOI18N
        boton_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_8ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 80, 70));

        boton_9.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        boton_9.setForeground(new java.awt.Color(139, 152, 169));
        boton_9.setText("9");
        boton_9.setContentAreaFilled(false);
        boton_9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AB.png"))); // NOI18N
        boton_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_9ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 80, 70));

        boton_P.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        boton_P.setForeground(new java.awt.Color(139, 152, 169));
        boton_P.setText(".");
        boton_P.setContentAreaFilled(false);
        boton_P.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_P.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AB.png"))); // NOI18N
        boton_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_PActionPerformed(evt);
            }
        });
        getContentPane().add(boton_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 570, 80, 70));

        boton_5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        boton_5.setForeground(new java.awt.Color(139, 152, 169));
        boton_5.setText("5");
        boton_5.setContentAreaFilled(false);
        boton_5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AB.png"))); // NOI18N
        boton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_5ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 80, 70));

        boton_2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        boton_2.setForeground(new java.awt.Color(139, 152, 169));
        boton_2.setText("2");
        boton_2.setContentAreaFilled(false);
        boton_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AB.png"))); // NOI18N
        boton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_2ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 80, 70));

        boton_3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        boton_3.setForeground(new java.awt.Color(139, 152, 169));
        boton_3.setText("3");
        boton_3.setContentAreaFilled(false);
        boton_3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AB.png"))); // NOI18N
        boton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_3ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 80, 70));

        boton_4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        boton_4.setForeground(new java.awt.Color(139, 152, 169));
        boton_4.setText("4");
        boton_4.setContentAreaFilled(false);
        boton_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AB.png"))); // NOI18N
        boton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_4ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 390, 80, 70));

        boton_0.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        boton_0.setForeground(new java.awt.Color(139, 152, 169));
        boton_0.setText("0");
        boton_0.setContentAreaFilled(false);
        boton_0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AB.png"))); // NOI18N
        boton_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_0ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 80, 70));

        boton_C.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        boton_C.setForeground(new java.awt.Color(139, 152, 169));
        boton_C.setText("C");
        boton_C.setContentAreaFilled(false);
        boton_C.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_C.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AB.png"))); // NOI18N
        boton_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_CActionPerformed(evt);
            }
        });
        getContentPane().add(boton_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, 80, 70));

        boton_1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        boton_1.setForeground(new java.awt.Color(139, 152, 169));
        boton_1.setText("1");
        boton_1.setContentAreaFilled(false);
        boton_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AB.png"))); // NOI18N
        boton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_1ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 480, 80, 70));

        etiketa_Resultado.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        etiketa_Resultado.setForeground(new java.awt.Color(255, 255, 255));
        etiketa_Resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiketa_Resultado.setText("Operacion. . .");
        getContentPane().add(etiketa_Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 400, 110));

        etiketa_Operacion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        etiketa_Operacion.setForeground(new java.awt.Color(255, 255, 255));
        etiketa_Operacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(etiketa_Operacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 200, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EF.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 440, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EA_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 240, 40));

        etiketa_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoCalc.png"))); // NOI18N
        getContentPane().add(etiketa_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_CActionPerformed
        etiketa_Operacion.setText("");
        etiketa_Resultado.setText("");
    }//GEN-LAST:event_boton_CActionPerformed

    private void boton_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_7ActionPerformed
        addNumber("7");
        boton_Igual.doClick();
    }//GEN-LAST:event_boton_7ActionPerformed

    private void boton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_4ActionPerformed
        addNumber("4");
        boton_Igual.doClick();
    }//GEN-LAST:event_boton_4ActionPerformed

    private void boton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_1ActionPerformed
        addNumber("1");
        boton_Igual.doClick();
    }//GEN-LAST:event_boton_1ActionPerformed

    private void boton_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_8ActionPerformed
        addNumber("8");
        boton_Igual.doClick();
    }//GEN-LAST:event_boton_8ActionPerformed

    private void boton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_5ActionPerformed
        addNumber("5");
        boton_Igual.doClick();
    }//GEN-LAST:event_boton_5ActionPerformed

    private void boton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_2ActionPerformed
        addNumber("2");
        boton_Igual.doClick();
    }//GEN-LAST:event_boton_2ActionPerformed

    private void boton_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_0ActionPerformed
        addNumber("0");
        boton_Igual.doClick();
    }//GEN-LAST:event_boton_0ActionPerformed

    private void boton_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_9ActionPerformed
        addNumber("9");
        boton_Igual.doClick();
    }//GEN-LAST:event_boton_9ActionPerformed

    private void boton_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_6ActionPerformed
        addNumber("6");
        boton_Igual.doClick();
    }//GEN-LAST:event_boton_6ActionPerformed

    private void boton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_3ActionPerformed
        addNumber("3");
        boton_Igual.doClick();
    }//GEN-LAST:event_boton_3ActionPerformed

    private void boton_EntreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_EntreActionPerformed
        addNumber("/");
       
    }//GEN-LAST:event_boton_EntreActionPerformed

    private void boton_PorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_PorActionPerformed
        addNumber("*");
        
    }//GEN-LAST:event_boton_PorActionPerformed

    private void boton_MenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_MenosActionPerformed
        addNumber("-");
        
    }//GEN-LAST:event_boton_MenosActionPerformed

    private void boton_MasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_MasActionPerformed
        addNumber("+");
        
    }//GEN-LAST:event_boton_MasActionPerformed

    private void boton_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_PActionPerformed
        addNumber(".");
        boton_Igual.doClick();
    }//GEN-LAST:event_boton_PActionPerformed

    private void boton_IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_IgualActionPerformed
        
        try {
           String resultado =  se.eval(etiketa_Operacion.getText()).toString();
           etiketa_Resultado.setText(resultado);
        } catch (Exception e) {
            etiketa_Operacion.setText("Error");
        }

        
    }//GEN-LAST:event_boton_IgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_0;
    private javax.swing.JButton boton_1;
    private javax.swing.JButton boton_2;
    private javax.swing.JButton boton_3;
    private javax.swing.JButton boton_4;
    private javax.swing.JButton boton_5;
    private javax.swing.JButton boton_6;
    private javax.swing.JButton boton_7;
    private javax.swing.JButton boton_8;
    private javax.swing.JButton boton_9;
    private javax.swing.JButton boton_C;
    private javax.swing.JButton boton_Entre;
    private javax.swing.JButton boton_Igual;
    private javax.swing.JButton boton_Mas;
    private javax.swing.JButton boton_Menos;
    private javax.swing.JButton boton_P;
    private javax.swing.JButton boton_Por;
    private javax.swing.JLabel etiketa_Fondo;
    private javax.swing.JLabel etiketa_Operacion;
    private javax.swing.JLabel etiketa_Resultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    public void addNumber(String digito){
        etiketa_Operacion.setText(etiketa_Operacion.getText() + digito);
    }
    
}
