/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author user
 */
public class Fecha extends javax.swing.JFrame {
  
   
    String Mes,Mes1,Año,Año1;
    public static String guardoA,guardoA2,guardoM,guardoM2;
    /**
     * Creates new form Fecha
     */
    public Fecha() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/Logo Final.png")));
        setSize(477, 337);
        setLocationRelativeTo(null);
        setResizable(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_año1 = new javax.swing.JTextField();
        txt_mes = new javax.swing.JTextField();
        txt_año = new javax.swing.JTextField();
        txt_mes1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        boton_OK = new javax.swing.JButton();
        boton_Cerrar = new javax.swing.JButton();
        etiketa_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(16, 63, 116));
        jLabel3.setText("Hesta:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 215, -1, -1));

        jLabel4.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(16, 63, 116));
        jLabel4.setText("Ingresa el Rango");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(16, 63, 116));
        jLabel5.setText("De Fechas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(16, 63, 116));
        jLabel6.setText("/");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        txt_año1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_año1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_año1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 80, 40));

        txt_mes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_mes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 50, 40));

        txt_año.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_año.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_año, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 80, 40));

        txt_mes1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_mes1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_mes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 50, 40));

        jLabel7.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(16, 63, 116));
        jLabel7.setText("Desde:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(16, 63, 116));
        jLabel8.setText("/");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(16, 63, 116));
        jLabel9.setText("Mes");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(16, 63, 116));
        jLabel10.setText("AÑO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        boton_OK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonOK - copia.png"))); // NOI18N
        boton_OK.setContentAreaFilled(false);
        boton_OK.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonOK1.png"))); // NOI18N
        boton_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_OKActionPerformed(evt);
            }
        });
        getContentPane().add(boton_OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 100, 40));

        boton_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        boton_Cerrar.setContentAreaFilled(false);
        boton_Cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar2.png"))); // NOI18N
        boton_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_CerrarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 60, 50));

        etiketa_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_AZ.png"))); // NOI18N
        getContentPane().add(etiketa_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_OKActionPerformed
        
         int validacion = 0;
        
        
        guardoM = txt_mes.getText().trim();
        guardoM2 = txt_mes1.getText().trim();
        guardoA = txt_año.getText().trim();
        guardoA2 = txt_año1.getText().trim();
      
        
       if(guardoM.equals("")){
            validacion++;
        }else if(guardoM2.equals("")){
            validacion++;
        }else if(guardoA.equals("")){
            validacion++;
        }else if(guardoA2.equals("")){
            validacion++;
        }
        if(validacion == 0){
            JOptionPane.showMessageDialog(null, "los datos se ingresaron correctamente, para ver las ganancias preciona el botton buscar");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "deves llenar todos los campios ");
        }
        
    }//GEN-LAST:event_boton_OKActionPerformed

    private void boton_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_CerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_boton_CerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fecha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Cerrar;
    private javax.swing.JButton boton_OK;
    private javax.swing.JLabel etiketa_Fondo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_año;
    private javax.swing.JTextField txt_año1;
    private javax.swing.JTextField txt_mes;
    private javax.swing.JTextField txt_mes1;
    // End of variables declaration//GEN-END:variables

 public void botones() {

        boton_OK.setOpaque(false);
        boton_OK.setBorderPainted(false);
        boton_OK.setContentAreaFilled(false);

        

    }

}
