/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

/**
 *
 * @author user
 */
public class Ganancias extends javax.swing.JFrame {

    String user = "";
    String Dia, Mes, Annio;
    String fecha;
    int Vendidos;
     

    /**
     * Creates new form Ganancias
     */

    public Ganancias() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/Logo Final.png")));
        user = Log_in.user;

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        setResizable(false);
        setLocationRelativeTo(null);//metodo para sentrar mi interfas
        setTitle("Ganancias -secion de " + user);//pongo el titulo

        txtP_instrucciones.setText("para insertar alguna lectura\n"
                + "deves precionar el boton\n"
                + "insertar, si deseas ver las lecturas\n"
                + "y ganancias preciona mostrar");

        txtP_instrucciones.setVisible(false);
        txt_mostrar_precio.setVisible(false);
        txt_Ganancia.setVisible(false);
        txt_Ganancia.setVisible(false);
        txt_Vasos.setVisible(false);
        txt_lec_final.setVisible(false);
        txt_lec_inicial.setVisible(false);

        etiketa_Ganancia.setVisible(false);
        etiketa_Lec_Final.setVisible(false);
        etiketa_Lec_inicial.setVisible(false);
        etiketa_Precio.setVisible(false);
        txt_Vasos.setVisible(false);
        etiketa_Fecha_egistro.setVisible(false);
        etiketa_Fecha_egistro.setVisible(false);
        txt_Ganancia.setVisible(false);

        txt_fecha.setVisible(false);
        etiketa_Vasos.setVisible(false);

        etiketa_Ganancia.setText("Ganancia:");
        etiketa_Lec_Final.setText("Lec Final:");
        etiketa_Lec_inicial.setText("Lec inicial:");
        etiketa_Precio.setText("Precio");
        etiketa_Vasos.setText("Cafes Vendidos");
        etiketa_fecha.setText("Fecha Registro");
        etiketa_Vasos.setText("Vasos");

        Calendar cl = Calendar.getInstance();
        Dia = Integer.toString(cl.get(Calendar.DATE));
        Mes = Integer.toString(cl.get(Calendar.MONTH) + 1);
        Annio = Integer.toString(cl.get(Calendar.YEAR));

        fecha = Dia + "/" + Mes + "/" + Annio;

        etiketa_fecha.setText(fecha);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_fecha = new javax.swing.JTextField();
        boton_Insaetar = new javax.swing.JButton();
        Boton_Mostrar = new javax.swing.JButton();
        etiketa_Lec_Final = new javax.swing.JLabel();
        txt_lec_inicial = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtP_instrucciones = new javax.swing.JTextPane();
        txt_mostrar_precio = new javax.swing.JTextField();
        txt_lec_final = new javax.swing.JTextField();
        txt_Ganancia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        etiketa_fecha = new javax.swing.JLabel();
        etiketa_Ganancia = new javax.swing.JLabel();
        etiketa_Lec_inicial = new javax.swing.JLabel();
        etiketa_Fecha_egistro = new javax.swing.JLabel();
        etiketa_Vasos = new javax.swing.JLabel();
        txt_Vasos = new javax.swing.JTextField();
        etiketa_Precio = new javax.swing.JLabel();
        etiketa_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_fecha.setBackground(new java.awt.Color(198, 123, 99));
        txt_fecha.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txt_fecha.setForeground(new java.awt.Color(255, 255, 255));
        txt_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fecha.setToolTipText("");
        txt_fecha.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txt_fecha.setDoubleBuffered(true);
        txt_fecha.setEnabled(false);
        getContentPane().add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 120, 50));

        boton_Insaetar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_ insertar.png"))); // NOI18N
        boton_Insaetar.setContentAreaFilled(false);
        boton_Insaetar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_ insertar2.png"))); // NOI18N
        boton_Insaetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_InsaetarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Insaetar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 140, 80));

        Boton_Mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Mostrar.png"))); // NOI18N
        Boton_Mostrar.setContentAreaFilled(false);
        Boton_Mostrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Mostrar2.png"))); // NOI18N
        Boton_Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_MostrarActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 220, 110));

        etiketa_Lec_Final.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiketa_Lec_Final.setForeground(new java.awt.Color(165, 86, 55));
        etiketa_Lec_Final.setText("Fecha");
        getContentPane().add(etiketa_Lec_Final, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txt_lec_inicial.setBackground(new java.awt.Color(198, 123, 99));
        txt_lec_inicial.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txt_lec_inicial.setForeground(new java.awt.Color(255, 255, 255));
        txt_lec_inicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_lec_inicial.setToolTipText("");
        txt_lec_inicial.setBorder(null);
        txt_lec_inicial.setDoubleBuffered(true);
        txt_lec_inicial.setEnabled(false);
        getContentPane().add(txt_lec_inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 200, 50));

        txtP_instrucciones.setBackground(new java.awt.Color(198, 123, 99));
        txtP_instrucciones.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtP_instrucciones.setForeground(new java.awt.Color(198, 123, 99));
        txtP_instrucciones.setCaretColor(new java.awt.Color(198, 123, 99));
        txtP_instrucciones.setDragEnabled(true);
        txtP_instrucciones.setEnabled(false);
        jScrollPane1.setViewportView(txtP_instrucciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 270, 130));

        txt_mostrar_precio.setBackground(new java.awt.Color(198, 123, 99));
        txt_mostrar_precio.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txt_mostrar_precio.setForeground(new java.awt.Color(255, 255, 255));
        txt_mostrar_precio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_mostrar_precio.setToolTipText("");
        txt_mostrar_precio.setBorder(null);
        txt_mostrar_precio.setDoubleBuffered(true);
        txt_mostrar_precio.setEnabled(false);
        getContentPane().add(txt_mostrar_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 80, 50));

        txt_lec_final.setBackground(new java.awt.Color(198, 123, 99));
        txt_lec_final.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txt_lec_final.setForeground(new java.awt.Color(255, 255, 255));
        txt_lec_final.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_lec_final.setToolTipText("");
        txt_lec_final.setBorder(null);
        txt_lec_final.setDoubleBuffered(true);
        txt_lec_final.setEnabled(false);
        getContentPane().add(txt_lec_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 200, 50));

        txt_Ganancia.setBackground(new java.awt.Color(198, 123, 99));
        txt_Ganancia.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txt_Ganancia.setForeground(new java.awt.Color(255, 255, 255));
        txt_Ganancia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Ganancia.setToolTipText("");
        txt_Ganancia.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txt_Ganancia.setDoubleBuffered(true);
        txt_Ganancia.setEnabled(false);
        getContentPane().add(txt_Ganancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 120, 50));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(107, 52, 36));
        jLabel3.setText("Ganancias");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        etiketa_fecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        etiketa_fecha.setForeground(new java.awt.Color(165, 86, 55));
        etiketa_fecha.setText("Fecha");
        getContentPane().add(etiketa_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        etiketa_Ganancia.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiketa_Ganancia.setForeground(new java.awt.Color(165, 86, 55));
        etiketa_Ganancia.setText("Fecha");
        getContentPane().add(etiketa_Ganancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        etiketa_Lec_inicial.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiketa_Lec_inicial.setForeground(new java.awt.Color(165, 86, 55));
        etiketa_Lec_inicial.setText("Fecha");
        getContentPane().add(etiketa_Lec_inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        etiketa_Fecha_egistro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiketa_Fecha_egistro.setForeground(new java.awt.Color(165, 86, 55));
        etiketa_Fecha_egistro.setText("Fecha:");
        getContentPane().add(etiketa_Fecha_egistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        etiketa_Vasos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiketa_Vasos.setForeground(new java.awt.Color(165, 86, 55));
        etiketa_Vasos.setText("Fecha");
        getContentPane().add(etiketa_Vasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        txt_Vasos.setBackground(new java.awt.Color(198, 123, 99));
        txt_Vasos.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txt_Vasos.setForeground(new java.awt.Color(255, 255, 255));
        txt_Vasos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Vasos.setToolTipText("");
        txt_Vasos.setBorder(null);
        txt_Vasos.setDoubleBuffered(true);
        txt_Vasos.setEnabled(false);
        getContentPane().add(txt_Vasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 80, 50));

        etiketa_Precio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiketa_Precio.setForeground(new java.awt.Color(165, 86, 55));
        etiketa_Precio.setText("Fecha");
        getContentPane().add(etiketa_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        etiketa_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_Ga.png"))); // NOI18N
        getContentPane().add(etiketa_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 690, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_MostrarActionPerformed
        int id = 0;
        String guardoV, guardoG;
        txtP_instrucciones.setVisible(true);
        txt_mostrar_precio.setVisible(true);
        txt_Ganancia.setVisible(true);
        txt_Ganancia.setVisible(true);
        txt_Vasos.setVisible(true);
        txt_lec_final.setVisible(true);
        txt_lec_inicial.setVisible(true);

        etiketa_Ganancia.setVisible(true);
        etiketa_Lec_Final.setVisible(true);
        etiketa_Lec_inicial.setVisible(true);
        etiketa_Precio.setVisible(true);
        txt_Vasos.setVisible(true);
        etiketa_Fecha_egistro.setVisible(true);

        etiketa_Fecha_egistro.setVisible(true);
        txt_Ganancia.setVisible(true);

        txt_Ganancia.setVisible(true);
        txt_fecha.setVisible(true);
        etiketa_Vasos.setVisible(true);

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "SELECT fecha, lec_inicial, lec_final, cafes_vendidos, ganancia, precio, ID FROM ingresos WHERE ID=(SELECT max(ID) FROM ingresos)");
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {

                txt_fecha.setText(rs.getString("fecha"));
                txt_lec_inicial.setText(rs.getString("lec_inicial"));
                txt_lec_final.setText(rs.getString("lec_final"));
                guardoG = Integer.toString(rs.getInt("ganancia"));
                txt_Ganancia.setText(guardoG);
                txt_mostrar_precio.setText(rs.getString("precio"));
                guardoV = Integer.toString(rs.getInt("cafes_vendidos"));
                txt_Vasos.setText(guardoV);
                id = rs.getInt("ID");
            }
            
            
            cn.close();

        } catch (SQLException e) {
            System.err.println("error al consultar los datos de la vase de datso ");
        }

        txtP_instrucciones.setText("has seleccionado el boton ganancias \n"
                + "en el cual podras ver todos los abanses \n"
                + "que ha tenido la maquina hasta haora");

    }//GEN-LAST:event_Boton_MostrarActionPerformed

    private void boton_InsaetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_InsaetarActionPerformed
        Insertarr mensajero = new Insertarr();
        mensajero.setVisible(true);
    }//GEN-LAST:event_boton_InsaetarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ganancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ganancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ganancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ganancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ganancias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Mostrar;
    private javax.swing.JButton boton_Insaetar;
    private javax.swing.JLabel etiketa_Fecha_egistro;
    private javax.swing.JLabel etiketa_Fondo;
    private javax.swing.JLabel etiketa_Ganancia;
    private javax.swing.JLabel etiketa_Lec_Final;
    private javax.swing.JLabel etiketa_Lec_inicial;
    private javax.swing.JLabel etiketa_Precio;
    private javax.swing.JLabel etiketa_Vasos;
    private javax.swing.JLabel etiketa_fecha;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtP_instrucciones;
    private javax.swing.JTextField txt_Ganancia;
    private javax.swing.JTextField txt_Vasos;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_lec_final;
    private javax.swing.JTextField txt_lec_inicial;
    private javax.swing.JTextField txt_mostrar_precio;
    // End of variables declaration//GEN-END:variables

    public void Fecha() {

    }

    private String toString(int Vendidos) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
