/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

import ventanas.Informacion_usuario;


/**
 *
 * @author user
 */
public class Gestionar_Usuarios extends javax.swing.JFrame {
DefaultTableModel model = new DefaultTableModel();
public static int ID = 0;

    String user;
    
    /**
     * Creates new form Gestionar_Usuarios
     */
    public Gestionar_Usuarios() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/Logo Final.png")));
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        setSize(714, 488);
        
        
            Connection cn = Conexion.conectar();
            PreparedStatement pst;
            try {
                pst = cn.prepareStatement(
                        "select id_usuario,nombre_usuario,username,tipo_nivel from usuarios");
            
            
            ResultSet rs = pst.executeQuery();

            tabla_usuarios = new JTable(model);
            Scroll.setViewportView(tabla_usuarios);

            model.addColumn(" ");
            model.addColumn("Nombre");
            model.addColumn("UserName");
            model.addColumn("Nivel");
            while(rs.next()){
                
                Object[] fila = new Object[4];

                for (int i = 0; i < 4; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                 model.addRow(fila);
            }
            cn.close();
        } catch (SQLException ex) {
                Logger.getLogger(Gestionar_Usuarios.class.getName()).log(Level.SEVERE, null, ex);
       System.err.println("error al llenar la tabla" );
            JOptionPane.showMessageDialog(null, "error al mostrar informacion, porfavor contacta al administrador ");
        }
             
             
              tabla_usuarios.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                //filas
                int fila_point = tabla_usuarios.rowAtPoint(e.getPoint());
                //columnas
                int columna_poin = 0;

                if (fila_point > -1) {
                    ID = (int) model.getValueAt(fila_point, columna_poin);
                    System.err.println(ID);
                    Informacion_usuario mensajero = new Informacion_usuario();
                    mensajero.setVisible(true);

                }
            }
        });
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Boton_nuevo_usuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Scroll = new javax.swing.JScrollPane();
        tabla_usuarios = new javax.swing.JTable();
        boton_Cerrar = new javax.swing.JButton();
        botton_Minimisar = new javax.swing.JButton();
        etiketa_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuarios Registrados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        Boton_nuevo_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo usuario1.png"))); // NOI18N
        Boton_nuevo_usuario.setContentAreaFilled(false);
        Boton_nuevo_usuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo usuario.png"))); // NOI18N
        Boton_nuevo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_nuevo_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_nuevo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 140, 120));

        jLabel2.setText("Nuevo Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, -1));

        tabla_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Scroll.setViewportView(tabla_usuarios);

        getContentPane().add(Scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 720, 280));

        boton_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        boton_Cerrar.setContentAreaFilled(false);
        boton_Cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar2.png"))); // NOI18N
        boton_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_CerrarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 60, 50));

        botton_Minimisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimisar.png"))); // NOI18N
        botton_Minimisar.setContentAreaFilled(false);
        botton_Minimisar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimisar2.png"))); // NOI18N
        botton_Minimisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_MinimisarActionPerformed(evt);
            }
        });
        getContentPane().add(botton_Minimisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        etiketa_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_UR.png"))); // NOI18N
        getContentPane().add(etiketa_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 714, 488));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_nuevo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_nuevo_usuarioActionPerformed
        Nuevo_Usuario mensajero = new Nuevo_Usuario();
        mensajero. setVisible(true);
    }//GEN-LAST:event_Boton_nuevo_usuarioActionPerformed

    private void boton_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_CerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_boton_CerrarActionPerformed

    private void botton_MinimisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_MinimisarActionPerformed
        this.setState(Log_in.ICONIFIED);
    }//GEN-LAST:event_botton_MinimisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestionar_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestionar_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestionar_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestionar_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestionar_Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_nuevo_usuario;
    private javax.swing.JScrollPane Scroll;
    private javax.swing.JButton boton_Cerrar;
    private javax.swing.JButton botton_Minimisar;
    private javax.swing.JLabel etiketa_Fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTable tabla_usuarios;
    // End of variables declaration//GEN-END:variables
}
