/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Informacion_usuario extends javax.swing.JFrame {
int ID;
String nivel;
String nombre,username;
String combo;
int IDF ;
    /**
     * Creates new form Informacion_usuario
     */
    public Informacion_usuario() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/Logo Final.png")));
        ID = Gestionar_Usuarios.ID;
        setLocationRelativeTo(null);
        
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select nombre_usuario, username,tipo_nivel from usuarios where id_usuario = '" + ID + "'");
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                
                txt_nonbre.setText(rs.getString("nombre_usuario"));
                txt_username.setText(rs.getString("username"));
                cmb_nivel.setSelectedItem(rs.getString("tipo_nivel"));
                
               
                
            }
        }catch (SQLException e) {
            System.err.println("error en el vaciado de la informacio del equipo");
        }
        
       
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_nonbre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        boton_Cerrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txt_username = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmb_nivel = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        etiketa_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nivel del usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Informacion del usario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txt_nonbre.setBackground(new java.awt.Color(0, 0, 0));
        txt_nonbre.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        txt_nonbre.setForeground(new java.awt.Color(255, 255, 255));
        txt_nonbre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nonbre.setBorder(null);
        txt_nonbre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nonbreActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nonbre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 320, 50));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre para iniciar secion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        boton_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        boton_Cerrar.setContentAreaFilled(false);
        boton_Cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar2.png"))); // NOI18N
        boton_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_CerrarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 60, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        jButton1.setAutoscrolls(true);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar1.jpg.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 110, 100));

        txt_username.setBackground(new java.awt.Color(0, 0, 0));
        txt_username.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_username.setBorder(null);
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 160, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contraseña.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contraseña1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 160, 90));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre del usuario:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 65, -1, -1));

        cmb_nivel.setBackground(new java.awt.Color(0, 0, 0));
        cmb_nivel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmb_nivel.setForeground(new java.awt.Color(255, 255, 255));
        cmb_nivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Medio" }));
        getContentPane().add(cmb_nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 170, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 110, 100));

        etiketa_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_INU.png"))); // NOI18N
        getContentPane().add(etiketa_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 602, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nonbreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nonbreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nonbreActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void boton_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_CerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_boton_CerrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nombre = txt_nonbre.getText().trim();
        username = txt_username.getText().trim();
        combo = cmb_nivel.getSelectedItem().toString();
        if(!nombre.equals("") && !username.equals("")){

        try {
             java.sql.Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement("update usuarios set nombre_usuario = ?, username = ?, tipo_nivel = ? where id_usuario = '" + ID + "'");
                    pst.setString(1, nombre);
                    pst.setString(2,username );
                    pst.setString(3, combo);
                pst.executeUpdate();
                cn.close();
                
                Limpiar();
                Verde();
                JOptionPane.showMessageDialog(null, "modificacion exitosa");
                this.dispose();
        } catch (Exception e) {
            System.err.println("error");
        }
            
        }else{
            JOptionPane.showMessageDialog(null, "no has llenado los campos, para realizar un cambio");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CambiarContraseña mensajero = new CambiarContraseña();
        mensajero.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                int dialog = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(null, "¿Deseas eliminar a este usuario?", "Eliminar", dialog);
        if (resultado == 0) {
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "DELETE from usuarios WHERE id_usuario = '" + ID + "'");
                pst.executeUpdate();
                cn.close();
                JOptionPane.showMessageDialog(null, "se elimino el usuario con exito");
                this.dispose();
            } catch (SQLException e) {
                System.err.println("error al eliminar el insumo");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacion_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Cerrar;
    private javax.swing.JComboBox<String> cmb_nivel;
    private javax.swing.JLabel etiketa_Fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_nonbre;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

    public void Verde(){
        txt_nonbre.setBackground(Color.GREEN);
                txt_username.setBackground(Color.GREEN);
                
    }

    public void Limpiar() {
        
        txt_nonbre.setText("");
        txt_username.setText("");
    }

    private void setResizable(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
