/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author user
 */
public class Informacion_Registro extends javax.swing.JFrame {

    String user;
    int ID;
    String precio;
    String dia, mes, annio;

    /**
     * Creates new form Informacion_insumo
     */
    public Informacion_Registro() {
        initComponents();

        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/Logo Final.png")));
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ID = Gestionar_ingresos.ID_ingreso;
        user = Log_in.user;
        setSize(425, 422);
        setResizable(false);
        setTitle("Informacion del insumo -Sesion de " + user);
        setLocationRelativeTo(null);

        

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select lec_final, ganancia,fecha,cafes_vendidos  from ingresos where ID = '" + ID + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_Fecha.setText(rs.getString("fecha"));
                
                txt_LecFinal.setText(rs.getString("lec_final"));
                txt_CafeVendidos.setText(rs.getString("cafes_vendidos"));
                txt_Ganancia.setText(rs.getString("ganancia"));

            }
            cn.close();

        } catch (SQLException ex) {
            System.err.println("error al obtener los datos ");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txt_CafeVendidos = new javax.swing.JTextField();
        txt_Ganancia = new javax.swing.JTextField();
        txt_LecFinal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        etiketa_Mes2 = new javax.swing.JLabel();
        etiketa_Mes1 = new javax.swing.JLabel();
        txt_Fecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        etiketa_Mes = new javax.swing.JLabel();
        etiketa_Mes3 = new javax.swing.JLabel();
        etiketa_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(107, 52, 36));
        jLabel3.setText("Ingresos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        txt_CafeVendidos.setEditable(false);
        txt_CafeVendidos.setBackground(new java.awt.Color(116, 67, 40));
        txt_CafeVendidos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_CafeVendidos.setForeground(new java.awt.Color(255, 255, 255));
        txt_CafeVendidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_CafeVendidos.setActionCommand("<Not Set>");
        txt_CafeVendidos.setBorder(null);
        getContentPane().add(txt_CafeVendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 160, 40));

        txt_Ganancia.setEditable(false);
        txt_Ganancia.setBackground(new java.awt.Color(116, 67, 40));
        txt_Ganancia.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_Ganancia.setForeground(new java.awt.Color(255, 255, 255));
        txt_Ganancia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Ganancia.setActionCommand("<Not Set>");
        txt_Ganancia.setBorder(null);
        getContentPane().add(txt_Ganancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, 40));

        txt_LecFinal.setEditable(false);
        txt_LecFinal.setBackground(new java.awt.Color(116, 67, 40));
        txt_LecFinal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_LecFinal.setForeground(new java.awt.Color(255, 255, 255));
        txt_LecFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_LecFinal.setActionCommand("<Not Set>");
        txt_LecFinal.setBorder(null);
        getContentPane().add(txt_LecFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 180, 40));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 90, 100));

        etiketa_Mes2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiketa_Mes2.setForeground(new java.awt.Color(165, 86, 55));
        etiketa_Mes2.setText("Lec_Final:");
        getContentPane().add(etiketa_Mes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 110, 30));

        etiketa_Mes1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiketa_Mes1.setForeground(new java.awt.Color(165, 86, 55));
        etiketa_Mes1.setText("Ganancias:");
        getContentPane().add(etiketa_Mes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, 30));

        txt_Fecha.setEditable(false);
        txt_Fecha.setBackground(new java.awt.Color(116, 67, 40));
        txt_Fecha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_Fecha.setForeground(new java.awt.Color(255, 255, 255));
        txt_Fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Fecha.setActionCommand("<Not Set>");
        txt_Fecha.setBorder(null);
        getContentPane().add(txt_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 180, 40));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(107, 52, 36));
        jLabel4.setText("Informacion ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        etiketa_Mes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiketa_Mes.setForeground(new java.awt.Color(165, 86, 55));
        etiketa_Mes.setText("Cafes Vendidos:");
        getContentPane().add(etiketa_Mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, 30));

        etiketa_Mes3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiketa_Mes3.setForeground(new java.awt.Color(165, 86, 55));
        etiketa_Mes3.setText("Fecha del Registro:");
        getContentPane().add(etiketa_Mes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 180, 30));

        etiketa_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_INF.png"))); // NOI18N
        getContentPane().add(etiketa_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int dialog = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(null, "¿Deseas eliminar el Registro?", "Eliminar", dialog);
        if (resultado == 0) {
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "DELETE from ingresos WHERE ID = '" + ID + "'");
                pst.executeUpdate();
                cn.close();
                JOptionPane.showMessageDialog(null, "se elimino el ingreso con exito");
                this.dispose();
            } catch (SQLException e) {
                System.err.println("error al eliminar el ingreso");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
             java.sql.Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement("update ingresos set nombre_usuario = ?, username = ?, tipo_nivel = ? where id_usuario = '" + ID + "'");
                    pst.setString(1, "");
                    pst.setString(2, "");
                    pst.setString(3, "");
                pst.executeUpdate();
                cn.close();
                
                txt_CafeVendidos.setText("");
                txt_Fecha.setText("");
                txt_Ganancia.setText("");
                txt_LecFinal.setText("");
                
                JOptionPane.showMessageDialog(null, "modificacion exitosa");
                this.dispose();
        } catch (Exception e) {
            System.err.println("error");
        }
                

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacion_Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiketa_Fondo;
    private javax.swing.JLabel etiketa_Mes;
    private javax.swing.JLabel etiketa_Mes1;
    private javax.swing.JLabel etiketa_Mes2;
    private javax.swing.JLabel etiketa_Mes3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_CafeVendidos;
    private javax.swing.JTextField txt_Fecha;
    private javax.swing.JTextField txt_Ganancia;
    private javax.swing.JTextField txt_LecFinal;
    // End of variables declaration//GEN-END:variables
}
