/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author user
 */
public class Informacion_insumo extends javax.swing.JFrame {

    String user;
    int ID;
    String precio;
    String dia, mes, annio;

    /**
     * Creates new form Informacion_insumo
     */
    public Informacion_insumo() {
        initComponents();

        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/Logo Final.png")));
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ID = Gestionar_insumos.ID_insumo;
        user = Log_in.user;
        setSize(425, 422);
        setResizable(false);
        setTitle("Informacion del insumo -Sesion de " + user);
        setLocationRelativeTo(null);

        

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select tipo_insumo,dia,mes,año,precio from insumos where id_insumo = '" + ID + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                dia = rs.getString("dia");
                mes = rs.getString("mes");
                annio = rs.getString("año");
                txt_Fecha.setText(dia + "/" + mes + "/" + annio);
                txt_precio.setText(rs.getString("precio"));
                txt_Insumo.setText(rs.getString("tipo_insumo"));

            }
            cn.close();

        } catch (SQLException ex) {
            System.err.println("error al obtener los datos ");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txt_Insumo = new javax.swing.JTextField();
        txt_Fecha = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        etiketa_Mes2 = new javax.swing.JLabel();
        etiketa_Mes1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        etiketa_Mes = new javax.swing.JLabel();
        etiketa_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(107, 52, 36));
        jLabel3.setText("Insumo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        txt_Insumo.setEditable(false);
        txt_Insumo.setBackground(new java.awt.Color(116, 67, 40));
        txt_Insumo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_Insumo.setForeground(new java.awt.Color(255, 255, 255));
        txt_Insumo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Insumo.setActionCommand("<Not Set>");
        txt_Insumo.setBorder(null);
        getContentPane().add(txt_Insumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 40));

        txt_Fecha.setEditable(false);
        txt_Fecha.setBackground(new java.awt.Color(116, 67, 40));
        txt_Fecha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_Fecha.setForeground(new java.awt.Color(255, 255, 255));
        txt_Fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Fecha.setActionCommand("<Not Set>");
        txt_Fecha.setBorder(null);
        getContentPane().add(txt_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 180, 40));

        txt_precio.setBackground(new java.awt.Color(116, 67, 40));
        txt_precio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_precio.setForeground(new java.awt.Color(255, 255, 255));
        txt_precio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_precio.setActionCommand("<Not Set>");
        txt_precio.setBorder(null);
        getContentPane().add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 160, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar1.jpg.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 90, 100));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 90, 90));

        etiketa_Mes2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiketa_Mes2.setForeground(new java.awt.Color(165, 86, 55));
        etiketa_Mes2.setText("Precio:");
        getContentPane().add(etiketa_Mes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 80, 30));

        etiketa_Mes1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiketa_Mes1.setForeground(new java.awt.Color(165, 86, 55));
        etiketa_Mes1.setText("Fecha del Registro:");
        getContentPane().add(etiketa_Mes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 180, 30));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(107, 52, 36));
        jLabel4.setText("Informacion ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        etiketa_Mes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiketa_Mes.setForeground(new java.awt.Color(165, 86, 55));
        etiketa_Mes.setText("Insumo:");
        getContentPane().add(etiketa_Mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 80, 30));

        etiketa_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_INF.png"))); // NOI18N
        getContentPane().add(etiketa_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int dialog = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(null, "¿Deseas eliminar el insumo?", "Eliminar", dialog);
        if (resultado == 0) {
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "DELETE from insumos WHERE id_insumo = '" + ID + "'");
                pst.executeUpdate();
                cn.close();
                JOptionPane.showMessageDialog(null, "se elimino el insunmo con exito");
                this.dispose();
            } catch (SQLException e) {
                System.err.println("error al eliminar el insumo");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        precio = txt_precio.getText().trim();
        
        if(!precio.equals("")){
        try {
            String txtp = txt_precio.getText().trim();
            Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "UPDATE `insumos` SET  precio = ? where id_insumo ='" + ID +"'");
                
                pst.setString(1, txtp);
                
                pst.executeUpdate();
                
                cn.close();
                
                JOptionPane.showMessageDialog(null, "la modificacion de realizo con exito");
                
                this.dispose();
                
        } catch (SQLException e) {
            System.err.println("error al cambiar el precio");
        }
        }else{
            JOptionPane.showMessageDialog(null, "deves llenar los campos, para \n"
                    + "realizar una modificacion");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion_insumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion_insumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion_insumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion_insumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacion_insumo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiketa_Fondo;
    private javax.swing.JLabel etiketa_Mes;
    private javax.swing.JLabel etiketa_Mes1;
    private javax.swing.JLabel etiketa_Mes2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_Fecha;
    private javax.swing.JTextField txt_Insumo;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
