/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.sql.PreparedStatement;
import java.sql.ResultSet;

import clases.Conexion;


import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author user
 */
public class Ingresos extends javax.swing.JFrame {
    
    boolean nani = false;
    String guardoD = "", guardoD2 = "", guardoA = "", guardoA2 = "", guardoM = "", guardoM2 = "";
     String guardoG, guardoV, guardoI, guardoGG;
     int C_Vendidos, Ganancias, Insumos, Ganancia_General ;
     int bandera = 1;

    /**
     * Creates new form Ingresos
     */
    public Ingresos() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/Logo Final.png")));
    
        
        Etiketa_Ganancias.setVisible(false);
        txt_ganancias.setVisible(false);
        Etiketa_CafesVendidos.setVisible(false);
        txt_cagesVendidos.setVisible(false);
        txt_precioInsumo.setVisible(false);
        Etiketa_PrecioInsumo.setVisible(false);
        Etiketa_GananciasGeneral.setVisible(false);
        txt_GananciaGeneral.setVisible(false);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setSize(723, 511);
        setLocationRelativeTo(null);
        setResizable(false);
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_GananciaGeneral = new javax.swing.JTextField();
        Etiketa_GananciasGeneral = new javax.swing.JLabel();
        txt_precioInsumo = new javax.swing.JTextField();
        Etiketa_PrecioInsumo = new javax.swing.JLabel();
        txt_cagesVendidos = new javax.swing.JTextField();
        Etiketa_CafesVendidos = new javax.swing.JLabel();
        Etiketa_Ganancias = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_ganancias = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        etiketa_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_GananciaGeneral.setEditable(false);
        txt_GananciaGeneral.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(txt_GananciaGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 385, 160, 40));

        Etiketa_GananciasGeneral.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 24)); // NOI18N
        Etiketa_GananciasGeneral.setForeground(new java.awt.Color(255, 255, 255));
        Etiketa_GananciasGeneral.setText("Ganancia General:");
        getContentPane().add(Etiketa_GananciasGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 390, -1, -1));

        txt_precioInsumo.setEditable(false);
        txt_precioInsumo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(txt_precioInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 335, 160, 40));

        Etiketa_PrecioInsumo.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 24)); // NOI18N
        Etiketa_PrecioInsumo.setForeground(new java.awt.Color(255, 255, 255));
        Etiketa_PrecioInsumo.setText("Precio de los insumos:");
        getContentPane().add(Etiketa_PrecioInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        txt_cagesVendidos.setEditable(false);
        txt_cagesVendidos.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(txt_cagesVendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 285, 160, 40));

        Etiketa_CafesVendidos.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 24)); // NOI18N
        Etiketa_CafesVendidos.setForeground(new java.awt.Color(255, 255, 255));
        Etiketa_CafesVendidos.setText("Cafes Vendidos:");
        getContentPane().add(Etiketa_CafesVendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        Etiketa_Ganancias.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 24)); // NOI18N
        Etiketa_Ganancias.setForeground(new java.awt.Color(255, 255, 255));
        Etiketa_Ganancias.setText("Ganancia:");
        getContentPane().add(Etiketa_Ganancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Greaficar.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Graficar1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 120, 110));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lupa1.jpg.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lupa.jpg.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 120, 110));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario.jpg.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario1.jpg.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 120, 110));

        jLabel4.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buscar Ganancias");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        txt_ganancias.setEditable(false);
        txt_ganancias.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(txt_ganancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 235, 160, 40));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Graficar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Calendario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        etiketa_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_O.png"))); // NOI18N
        getContentPane().add(etiketa_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 730, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Fecha mensagero = new Fecha();
        mensagero.setVisible(true);
        bandera=3;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (bandera == 1) {
            JOptionPane.showMessageDialog(null, "No ingresaste datos, para ingresarlos seleccioa el boton Calendario");
        } else if (bandera == 3) {
            
            guardoA = Fecha.guardoA;
            guardoA2 = Fecha.guardoA2;
            guardoM = Fecha.guardoM;
            guardoM2 = Fecha.guardoM2;

            txt_ganancias.setVisible(true);
            Etiketa_Ganancias.setVisible(true);
            Etiketa_CafesVendidos.setVisible(true);
            txt_cagesVendidos.setVisible(true);
            txt_precioInsumo.setVisible(true);
            Etiketa_PrecioInsumo.setVisible(true);
            Etiketa_GananciasGeneral.setVisible(true);
            txt_GananciaGeneral.setVisible(true);
            
           
            try {
                java.sql.Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "SELECT sum(cafes_vendidos), sum(ganancia) from ingresos where año BETWEEN'" +guardoA+ "'AND'"+ guardoA2 +"'AND mes BETWEEN'"  + guardoM  +"'AND'" + guardoM2 + "'");
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    C_Vendidos = rs.getInt("sum(cafes_vendidos)");
                    Ganancias = rs.getInt("sum(ganancia)");
                }
                guardoG = Integer.toString(Ganancias);
                guardoV = Integer.toString(C_Vendidos);

                txt_ganancias.setText(guardoG);
                txt_cagesVendidos.setText(guardoV);

                cn.close();
                bandera =3;
            } catch (Exception e) {
                System.err.print("error");
            }
            System.out.println(guardoM);
            System.out.println(guardoM2);
            try {

                java.sql.Connection cn2 = Conexion.conectar();
                PreparedStatement pst2 = cn2.prepareStatement("select sum(precio) from insumos where año BETWEEN'" +guardoA+ "'AND'"+ guardoA2 +"'AND mes BETWEEN'"  + guardoM  +"'AND'" + guardoM2 + "'");
                ResultSet rs2 = pst2.executeQuery();
                if (rs2.next()) {
                    Insumos = rs2.getInt("sum(precio)");

                }
                guardoI = Integer.toString(Insumos);
                txt_precioInsumo.setText(guardoI);

                Ganancia_General = Ganancias - Insumos;
                guardoGG = Integer.toString(Ganancia_General);
                txt_GananciaGeneral.setText(guardoGG);
            } catch (Exception e) {
                
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(bandera == 3){
            repaint();
            nani = true;
        }else{
            JOptionPane.showMessageDialog(null, "para fraficar deves consultar los datos");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Etiketa_CafesVendidos;
    private javax.swing.JLabel Etiketa_Ganancias;
    private javax.swing.JLabel Etiketa_GananciasGeneral;
    private javax.swing.JLabel Etiketa_PrecioInsumo;
    private javax.swing.JLabel etiketa_Fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_GananciaGeneral;
    private javax.swing.JTextField txt_cagesVendidos;
    private javax.swing.JTextField txt_ganancias;
    private javax.swing.JTextField txt_precioInsumo;
    // End of variables declaration//GEN-END:variables

    public int MayorValor(int vendidos,int ganancias,int gananciasgenerales,int insumos){
        if(vendidos>ganancias && vendidos>gananciasgenerales && vendidos>insumos){
            return vendidos;
        }else if(ganancias>gananciasgenerales && ganancias>insumos){
            return ganancias;
        }else{
            return insumos;
        }
    }
    
    public void paint(Graphics g){
        super.paint(g);
        
        if(nani =true){
            String string_ganancias=txt_ganancias.getText().trim();
            String string_vendidos=txt_cagesVendidos.getText().trim();
            String string_gananciasgenerales=txt_GananciaGeneral.getText().trim();
            String string_insumos=txt_precioInsumo.getText().trim();
            
            int int_ganancias = Integer.parseInt(string_ganancias);
            int int_vendidos = Integer.parseInt(string_vendidos);
            int int_gananciasgenerales = Integer.parseInt(string_gananciasgenerales);
            int int_insumos = Integer.parseInt(string_insumos);
            
            int valor_Mayor = MayorValor(C_Vendidos, Ganancias, Ganancia_General, Insumos);
            
            int largo_ganancias = int_ganancias*300/valor_Mayor;
            int largo_vendidos = int_vendidos*300/valor_Mayor;
            int largo_gananciasgenerales = int_gananciasgenerales*300/valor_Mayor;
            int largo_insumos = int_insumos*300/valor_Mayor;
            
            g.setColor(java.awt.Color.black);
            g.fillRect(100, 100, largo_insumos, 60);
            g.drawString("Costo insumos", 10, 135);
            
            g.setColor(java.awt.Color.GREEN);
            g.fillRect(100, 200, largo_gananciasgenerales, 60);
            g.drawString("Ganancias", 10, 235);
            
            g.setColor(java.awt.Color.WHITE);
            g.fillRect(100, 300, largo_vendidos, 60);
            g.drawString("C_Vendidos", 10, 355);
            
           
        }
        
    }
    
}
