/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author user
 */
public class Insertarr extends javax.swing.JFrame {
    String Dia, Mes, Annio;
    String user, fecha, precioo;
    int precio, Lec_Final, Lec_Inicial, ganancia, cafes;
    String guardoLecI, guardoLecF, guardoP;

    /**
     * Creates new form Insertarr
     */
    public Insertarr() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/Logo Final.png")));
        user = Log_in.user;
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        setSize(422, 412);
        setResizable(false);
        setLocationRelativeTo(null);//metodo para sentrar mi interfas
        setTitle("Insertar -secion de " + user);//pongo el titulo

        

        Calendar cl = Calendar.getInstance();
        Dia = Integer.toString(cl.get(Calendar.DATE));
        Mes = Integer.toString(cl.get(Calendar.MONTH) + 1);
        Annio = Integer.toString(cl.get(Calendar.YEAR));

        fecha = Dia + "/" + Mes + "/" + Annio;

        txt_Fecha.setText(fecha);
        
        try {
            
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select precio FROM ingresos WHERE ID=(SELECT max(ID) FROM ingresos)");
             ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
            txt_Precio.setText(rs.getNString("precio"));
            }
            
        } catch (Exception e) {
        }

        this.repaint();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton_Insaetar = new javax.swing.JButton();
        txt_Lec_Final = new javax.swing.JTextField();
        etiketa_Vasos1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_Precio = new javax.swing.JTextField();
        txt_Fecha = new javax.swing.JTextField();
        etiketa_Vasos2 = new javax.swing.JLabel();
        etiketa_Vasos3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        etiketa_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_Insaetar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_ insertar.png"))); // NOI18N
        boton_Insaetar.setContentAreaFilled(false);
        boton_Insaetar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_ insertar2.png"))); // NOI18N
        boton_Insaetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_InsaetarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Insaetar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 140, 80));

        txt_Lec_Final.setBackground(new java.awt.Color(198, 123, 99));
        txt_Lec_Final.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txt_Lec_Final.setForeground(new java.awt.Color(255, 255, 255));
        txt_Lec_Final.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Lec_Final.setToolTipText("");
        txt_Lec_Final.setActionCommand("<Not Set>");
        txt_Lec_Final.setBorder(null);
        getContentPane().add(txt_Lec_Final, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 350, 50));

        etiketa_Vasos1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiketa_Vasos1.setForeground(new java.awt.Color(255, 255, 255));
        etiketa_Vasos1.setText("Ingresa la lectira final de hoy:");
        getContentPane().add(etiketa_Vasos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jButton1.setBackground(new java.awt.Color(198, 123, 99));
        jButton1.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cambiar precio");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 120, 40));

        txt_Precio.setBackground(new java.awt.Color(198, 123, 99));
        txt_Precio.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txt_Precio.setForeground(new java.awt.Color(255, 255, 255));
        txt_Precio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Precio.setToolTipText("");
        txt_Precio.setActionCommand("<Not Set>");
        txt_Precio.setBorder(null);
        txt_Precio.setDoubleBuffered(true);
        txt_Precio.setEnabled(false);
        txt_Precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PrecioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 150, 50));

        txt_Fecha.setBackground(new java.awt.Color(198, 123, 99));
        txt_Fecha.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txt_Fecha.setForeground(new java.awt.Color(255, 255, 255));
        txt_Fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Fecha.setToolTipText("");
        txt_Fecha.setActionCommand("<Not Set>");
        txt_Fecha.setBorder(null);
        txt_Fecha.setDoubleBuffered(true);
        txt_Fecha.setEnabled(false);
        getContentPane().add(txt_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 150, 50));

        etiketa_Vasos2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiketa_Vasos2.setForeground(new java.awt.Color(255, 255, 255));
        etiketa_Vasos2.setText("Precio:");
        getContentPane().add(etiketa_Vasos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, 30));

        etiketa_Vasos3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiketa_Vasos3.setForeground(new java.awt.Color(255, 255, 255));
        etiketa_Vasos3.setText("Fecha:");
        getContentPane().add(etiketa_Vasos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Insertar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, -1));

        etiketa_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_ins_1.png"))); // NOI18N
        getContentPane().add(etiketa_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_InsaetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_InsaetarActionPerformed
        precio = Integer.parseInt(txt_Precio.getText().trim());
        Lec_Final = Integer.parseInt(txt_Lec_Final.getText().trim());
        fecha = txt_Fecha.getText().trim();

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select lec_final FROM ingresos WHERE ID=(SELECT max(ID) FROM ingresos)");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                Lec_Inicial = Integer.parseInt(rs.getString("lec_final"));
            }

            cafes = Lec_Final - Lec_Inicial;
            ganancia = cafes * precio;

            guardoLecI = Integer.toString(Lec_Inicial);
            
            guardoLecF = Integer.toString(Lec_Final);
            guardoP = Integer.toString(precio);
            

        } catch (SQLException e) {
            System.err.println("error al obtener la lectura inicial");
        }

        if (!txt_Lec_Final.equals("")) {
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "INSERT INTO ingresos values (?,?,?,?,?,?,?,?,?,?)");
                pst.setInt(1, 0);
                pst.setString(2, Dia);
                pst.setString(3, Mes);
                pst.setString(4, Annio);
                pst.setString(5, fecha);
                pst.setString(6, guardoLecI);
                pst.setString(7, guardoLecF);
                pst.setInt(8, cafes);
                pst.setString(9, guardoP);
                pst.setInt(10, ganancia);
                
                pst.executeUpdate();
                cn.close();
            } catch (SQLException e) {
                System.err.println("error al cargar los daros de la base");
            }
            JOptionPane.showMessageDialog(null, "El Registro se inserto correctamente");
            
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Deves llenar el campo que se pide");
        }

    }//GEN-LAST:event_boton_InsaetarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txt_Precio.enable(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_PrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insertarr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insertarr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insertarr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insertarr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insertarr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Insaetar;
    private javax.swing.JLabel etiketa_Fondo;
    private javax.swing.JLabel etiketa_Vasos1;
    private javax.swing.JLabel etiketa_Vasos2;
    private javax.swing.JLabel etiketa_Vasos3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_Fecha;
    private javax.swing.JTextField txt_Lec_Final;
    private javax.swing.JTextField txt_Precio;
    // End of variables declaration//GEN-END:variables

    public void Fecha() {
        
    }
}
