/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.ImageIcon;
import java.sql.*;
import clases.Conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Log_in extends javax.swing.JFrame {

    public static String user = "";
    String pass = "";
    
    
    /**
     * Creates new form Log_in
     */
    public Log_in() {
        initComponents();
        
        //setIconImage(new ImageIcon(getClass().getResource("src/imagenes/pez.png")).getImage());
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/Logo Final.png")));
        setSize(556, 728);
        setResizable(false);//metodo para rue el usuario no modifique mi interfas
        setLocationRelativeTo(null);//metodo para sentrar mi interfas
        setTitle("Acceso al sistema");//pongo el titulo

        //colocar imagen de fondo
        

    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Logo Final.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botton_Minimisar = new javax.swing.JButton();
        botton_Cerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        boton_Continuar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_User = new javax.swing.JTextField();
        txt_contraseña = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        etiketa_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botton_Minimisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimisar2.png"))); // NOI18N
        botton_Minimisar.setContentAreaFilled(false);
        botton_Minimisar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimisar.png"))); // NOI18N
        botton_Minimisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_MinimisarActionPerformed(evt);
            }
        });
        getContentPane().add(botton_Minimisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 40, 40));

        botton_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar2.png"))); // NOI18N
        botton_Cerrar.setContentAreaFilled(false);
        botton_Cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        botton_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_CerrarActionPerformed(evt);
            }
        });
        getContentPane().add(botton_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 410, 410));

        boton_Continuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton continuar .png"))); // NOI18N
        boton_Continuar.setText("jButton1");
        boton_Continuar.setContentAreaFilled(false);
        boton_Continuar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton continuar 2.png"))); // NOI18N
        boton_Continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 541, 250, 120));

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 497, -1, -1));

        txt_User.setBackground(new java.awt.Color(186, 146, 109));
        txt_User.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        txt_User.setForeground(new java.awt.Color(255, 255, 255));
        txt_User.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_User.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_User.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_User.setDragEnabled(true);
        txt_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UserActionPerformed(evt);
            }
        });
        getContentPane().add(txt_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 290, 50));

        txt_contraseña.setBackground(new java.awt.Color(186, 146, 109));
        txt_contraseña.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_contraseña.setForeground(new java.awt.Color(255, 255, 255));
        txt_contraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_contraseña.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 250, -1));

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Creado por Sobera Sotomayor Iñaki®");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 670, -1, -1));

        etiketa_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Log_in.png"))); // NOI18N
        getContentPane().add(etiketa_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_ContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ContinuarActionPerformed
        pass = txt_contraseña.getText().trim();
        user = txt_User.getText().trim();

        if (!user.equals("") || !pass.equals("")) {
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "select tipo_nivel from usuarios where username = '" + user
                        + "' and password = '" + pass + "'");
                ResultSet rs = pst.executeQuery();
                
                if (rs.next()) {
                    String tipo_nivel = rs.getString("tipo_nivel");

                    if (tipo_nivel.equalsIgnoreCase("Administrador")) {
                        dispose();
                        new Administrador().setVisible(true);
                    }
                    if (tipo_nivel.equalsIgnoreCase("Medio")) {
                        dispose();
                        new Medio().setVisible(true);
                    } 
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Dotos de acceso incorrectos");
                    txt_contraseña.setText("");
                    txt_User.setText("");
                }

            } catch (SQLException e) {
                System.err.println("Error en el boton acceder " + e);
                JOptionPane.showMessageDialog(null, "Error al iniciar secion, conracte al administrador");
            }
        } else if(user.equals("") || pass.equals("")){
            JOptionPane.showMessageDialog(null, "Deves llenar los campos");
        }
        else{
            
            JOptionPane.showMessageDialog(null, "deves llenar todos los campos");
                
                }
    }//GEN-LAST:event_boton_ContinuarActionPerformed

    private void botton_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_CerrarActionPerformed
        int dialog = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(null, "¿Deseas salir del login?", "Salir", dialog);
        if (resultado == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_botton_CerrarActionPerformed

    private void botton_MinimisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_MinimisarActionPerformed
        this.setState(Log_in.ICONIFIED);
    }//GEN-LAST:event_botton_MinimisarActionPerformed

    private void txt_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Continuar;
    private javax.swing.JButton botton_Cerrar;
    private javax.swing.JButton botton_Minimisar;
    private javax.swing.JLabel etiketa_Fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_User;
    private javax.swing.JPasswordField txt_contraseña;
    // End of variables declaration//GEN-END:variables

    public void botones() {

        boton_Continuar.setOpaque(false);
        boton_Continuar.setBorderPainted(false);
        boton_Continuar.setContentAreaFilled(false);

        botton_Cerrar.setOpaque(false);
        botton_Cerrar.setBorderPainted(false);
        botton_Cerrar.setContentAreaFilled(false);

        botton_Minimisar.setOpaque(false);
        botton_Cerrar.setBorderPainted(false);
        botton_Cerrar.setContentAreaFilled(false);

    }
}
