/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static ventanas.Administrador.Secion_usuario;

/**
 *
 * @author user
 */
public class Medio extends javax.swing.JFrame {

    String user, nombre_usuario;

    public static int Secion_usuario;
     
    /**
     * Creates new form Medio
     */
    public Medio() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/Logo Final.png")));
         user = Log_in.user;
        Secion_usuario = 1;
        
        setSize(727, 316);
        setResizable(false);
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select nombre_usuario from usuarios where username = '" + user + "' ");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                nombre_usuario = rs.getString("nombre_usuario");
                etiketa_Bienbenida.setText("Secion de " + nombre_usuario);
            }
        } catch (Exception e) {
            System.err.println("erro en la coneccion en la interfaz administrador");
        }
       
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton_agregar_insumo = new javax.swing.JButton();
        boton_GestionarInsumos5 = new javax.swing.JButton();
        boton_GestionarInsumos2 = new javax.swing.JButton();
        etiketa_Bienbenida = new javax.swing.JLabel();
        boton_ganancias = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        etiketa_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_agregar_insumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo insumo.png"))); // NOI18N
        boton_agregar_insumo.setContentAreaFilled(false);
        boton_agregar_insumo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar insumo2.png"))); // NOI18N
        boton_agregar_insumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_agregar_insumoActionPerformed(evt);
            }
        });
        getContentPane().add(boton_agregar_insumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 130));

        boton_GestionarInsumos5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono.png"))); // NOI18N
        boton_GestionarInsumos5.setContentAreaFilled(false);
        boton_GestionarInsumos5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono1.png"))); // NOI18N
        boton_GestionarInsumos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_GestionarInsumos5ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_GestionarInsumos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 140, 130));

        boton_GestionarInsumos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aserca_de.png"))); // NOI18N
        boton_GestionarInsumos2.setContentAreaFilled(false);
        boton_GestionarInsumos2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aserca_de.1png.png"))); // NOI18N
        boton_GestionarInsumos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_GestionarInsumos2ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_GestionarInsumos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 130, 130));

        etiketa_Bienbenida.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        etiketa_Bienbenida.setForeground(new java.awt.Color(88, 33, 12));
        etiketa_Bienbenida.setText("jLabel1");
        getContentPane().add(etiketa_Bienbenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        boton_ganancias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ganancias.png"))); // NOI18N
        boton_ganancias.setContentAreaFilled(false);
        boton_ganancias.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ganancias2.png"))); // NOI18N
        boton_ganancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_gananciasActionPerformed(evt);
            }
        });
        getContentPane().add(boton_ganancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 140, 130));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(88, 56, 28));
        jLabel4.setText("Registros");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(88, 56, 28));
        jLabel5.setText("insertar insumo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(88, 56, 28));
        jLabel6.setText("Aserca de. . . ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(88, 56, 28));
        jLabel7.setText("Calculadora ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        etiketa_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_M.png"))); // NOI18N
        getContentPane().add(etiketa_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_agregar_insumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_agregar_insumoActionPerformed
        Agregar_Insumo mensajero = new Agregar_Insumo();
        mensajero.setVisible(true);
    }//GEN-LAST:event_boton_agregar_insumoActionPerformed

    private void boton_GestionarInsumos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_GestionarInsumos5ActionPerformed
        Calculadora mensajero = new Calculadora();
        mensajero.setVisible(true);
    }//GEN-LAST:event_boton_GestionarInsumos5ActionPerformed

    private void boton_GestionarInsumos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_GestionarInsumos2ActionPerformed
        JOptionPane.showMessageDialog(null, "Creador: Sobera Sotomayor Iñaki\n"
            + "(Para cualquier fallo en el sistema, porfavor comunicate\n"
            + "al 5539357116)");
    }//GEN-LAST:event_boton_GestionarInsumos2ActionPerformed

    private void boton_gananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_gananciasActionPerformed
        Ganancias mensajero = new Ganancias();
        mensajero.setVisible(true);
    }//GEN-LAST:event_boton_gananciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_GestionarInsumos2;
    private javax.swing.JButton boton_GestionarInsumos5;
    private javax.swing.JButton boton_agregar_insumo;
    private javax.swing.JButton boton_ganancias;
    private javax.swing.JLabel etiketa_Bienbenida;
    private javax.swing.JLabel etiketa_Fondo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
